/**
 * @module IEEEMarkdownExporter
 * @description Dynamic client-side Blob generator for IEEE Capstone Synopses.
 * Serializes active project data into an IEEE-compliant Markdown structure
 * and triggers a browser download via a dynamic Blob URL.
 */

import type { BlueprintContract } from '../../domain/contracts/blueprint.contract';
import type { RoadmapContract } from '../../domain/contracts/roadmap.contract';
import { computeCompletionPercentage } from '../../domain/contracts/roadmap.contract';

/**
 * Generates an IEEE-formatted Markdown synopsis from a project blueprint.
 *
 * @param blueprint - The project blueprint to serialize
 * @param roadmap - Optional roadmap for progress tracking section
 * @param studentName - The student's name for the author field
 * @returns A complete IEEE-formatted Markdown string
 * @throws Never — returns a minimal synopsis if inputs are incomplete
 *
 * @example
 * ```typescript
 * const markdown = generateIEEEMarkdown(blueprint, roadmap, 'Jane Doe');
 * ```
 */
export function generateIEEEMarkdown(
  blueprint: BlueprintContract,
  roadmap: RoadmapContract | null,
  studentName: string
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sections: string[] = [];

  // Title and metadata
  sections.push(`# ${blueprint.title}`);
  sections.push('');
  sections.push(`**Author:** ${studentName || 'Student'}`);
  sections.push(`**Date:** ${date}`);
  sections.push(`**Domain:** ${blueprint.targetDomain}`);
  sections.push(`**Feasibility Score:** ${blueprint.feasibilityScore}/100`);
  sections.push(`**Novelty Factor:** ${blueprint.novelty}`);
  sections.push(`**Estimated Duration:** ${blueprint.estimatedWeeks} weeks`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // Abstract
  sections.push('# Abstract');
  sections.push('');
  sections.push(blueprint.abstract);
  sections.push('');

  // Keywords
  sections.push('**Keywords:** ' + blueprint.techStack.map((t) => t.name).join(', '));
  sections.push('');
  sections.push('---');
  sections.push('');

  // System Architecture
  sections.push('## System Architecture');
  sections.push('');
  sections.push('The proposed system implements a multi-tier architecture:');
  sections.push('');
  sections.push('| Tier | Technology | Rationale |');
  sections.push('|------|-----------|-----------|');
  for (const entry of blueprint.techStack) {
    sections.push(`| ${entry.tier} | ${entry.name} | ${entry.rationale} |`);
  }
  sections.push('');

  // Features
  sections.push('## Core Features');
  sections.push('');
  for (const feature of blueprint.features) {
    sections.push(`### ${feature.priority}. ${feature.name}`);
    sections.push('');
    sections.push(feature.description);
    sections.push('');
  }

  // Improvements
  sections.push('## Future Improvements');
  sections.push('');
  for (const improvement of blueprint.improvements) {
    sections.push(`- **${improvement.title}** (${improvement.impact} Impact): ${improvement.description}`);
  }
  sections.push('');

  // Roadmap progress
  if (roadmap) {
    sections.push('## Development Progress');
    sections.push('');
    const percentage = computeCompletionPercentage(
      roadmap.completedMilestones,
      roadmap.totalMilestones
    );
    sections.push(`**Overall Completion:** ${percentage}% (${roadmap.completedMilestones}/${roadmap.totalMilestones} milestones)`);
    sections.push('');
    for (const phase of roadmap.phases) {
      sections.push(`### ${phase.label} (${phase.weekRange})`);
      sections.push('');
      for (const milestone of phase.milestones) {
        const check = milestone.state === 'Completed' ? '✅' : '⬜';
        sections.push(`- ${check} **Week ${milestone.weekNumber}:** ${milestone.title} — ${milestone.description}`);
      }
      sections.push('');
    }
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push(`*Synopsis generated by Project Prometheus — AI-Powered Capstone Compiler*`);
  sections.push(`*Generated on ${date}*`);

  return sections.join('\n');
}

/**
 * Triggers a browser download of the IEEE Synopsis as a Markdown file.
 * Creates a dynamic Blob URL and programmatically clicks a download link.
 *
 * @param blueprint - The project blueprint to export
 * @param roadmap - Optional roadmap for progress section
 * @param studentName - The student's name for the author field
 * @throws Never — fails silently if download cannot be triggered
 *
 * @example
 * ```typescript
 * downloadIEEESynopsis(blueprint, roadmap, 'Jane Doe');
 * // Triggers download: "ai-medical-imaging-triage-IEEE-Synopsis.md"
 * ```
 */
export function downloadIEEESynopsis(
  blueprint: BlueprintContract,
  roadmap: RoadmapContract | null,
  studentName: string
): void {
  const markdownContent = generateIEEEMarkdown(blueprint, roadmap, studentName);

  const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${blueprint.slug}-IEEE-Synopsis.md`;
  link.click();
  URL.revokeObjectURL(url);
}
